# Makefile

# Defaults
SIM ?= icarus
TOPLEVEL_LANG ?= verilog

VERILOG_SOURCES += c:/Users/User1/veri_env/example/papa/../child/rtl/mc1.v
VERILOG_SOURCES += c:/Users/User1/veri_env/example/papa/rtl/m1.v
VERILOG_SOURCES += c:/Users/User1/veri_env/example/papa/../child/rtl/mc2.v
VERILOG_SOURCES += c:/Users/User1/veri_env/example/papa/../child/../grandson/rtl/gs.v
VERILOG_SOURCES += c:/Users/User1/veri_env/example/papa/rtl/m2.v

TOPLEVEL = m1

MODULE = m1_tb

include $(shell cocotb-config --makefiles)/Makefile.sim